---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: edit the hosts file
      lineinfile:
        line: "ansible.xyzcorp.com 169.168.0.1"
        path: /etc/hosts

    - name: install elinks
      package:
        name: elinks
        state: latest

    - name: create user xyzcorp_audit
      user:
        name: xyzcorp_audit
        state: present

    - name: copy files motd
      copy:
        src: /home/ansible/motd
        dest: /etc/motd

    - name: copy files issue
      copy:
        src: /home/ansible/issue
        dest: /etc/issue

- hosts: network
  become: yes
  gather_facts: no
  tasks:
    - name: install nmap-ncat
      yum:
        name: nmap-ncat
        state: latest

    - name: create netwok user
      user:
        name: xyzcorp_network
        state: present

- hosts: sysadmin
  become: yes
  gather_facts: no
  tasks:
    - name: copy ansible scripts
      copy:
        src: /home/ansible/scripts.tgz
        dest: /mnt/storage
